# Generated by Django 5.1.4 on 2025-01-23 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='autor',
            field=models.CharField(default='Autor', max_length=100),
        ),
    ]
