# Generated by Django 5.1.4 on 2025-01-26 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0002_posts_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='link',
        ),
        migrations.AlterField(
            model_name='posts',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
    ]
