# Generated by Django 5.1.4 on 2025-01-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0003_remove_posts_link_alter_posts_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
