# Generated by Django 5.1.4 on 2025-01-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeriesUY', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plataforma',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='serie',
            name='puntuacion',
            field=models.FloatField(),
        ),
    ]
